FROM debian:jessie

RUN \
        set -ex \
    && \
        apt-get update && apt-get install -y \
            curl \
            libunwind8 \
            gettext\
            build-essential \
            libcurl4-openssl-dev \
            git \
            cmake \
            libssl-dev \
            valgrind \
            libglib2.0-dev \
            libavahi-client-dev \
    && \
        curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=843453 \
    && \
        mkdir -p /opt/dotnet && tar zxf dotnet.tar.gz -C /opt/dotnet \
    && \
        ln -s /opt/dotnet/dotnet /usr/local/bin
