FROM ubuntu:trusty

ENV PROXY_REPO https://github.com/Azure/iot-gateway-proxy
ENV COMMIT_ID master

RUN \
		set -ex \
	&& \
		apt-get update && apt-get install -y \
			build-essential \
			git \
			cmake \
			libssl-dev \
			libcurl4-openssl-dev \
			libglib2.0-dev

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
