FROM ubuntu:yakkety

RUN \
        set -ex \
    && \
        apt-get update && apt-get install -y \
            apt-transport-https \
            curl \
            build-essential \
            libcurl4-openssl-dev \
            git \
            cmake \
            libssl-dev \
            valgrind \
            libglib2.0-dev \
            libavahi-client-dev \
    && \
        sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list' \
    && \
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893 \
    && \
        apt-get update && apt-get install -y \
            dotnet-dev-1.0.1
