FROM alpine:3.5

RUN \
        set -ex \
    && \
        apk add --no-cache --virtual .fetch-deps \
            git \
            bash \
    && \
        apk add --no-cache --virtual .build-deps \
            cmake \
            build-base \
            gcc \
            abuild \
            binutils \
            make \
            libc-dev \
            curl-dev
